# Production Docker Compose configuration
# Use with: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

version: '3.8'

services:
  # Production application
  app-prod:
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    container_name: semantic-kernel-prod
    restart: unless-stopped
    environment:
      - USE_OLLAMA=true
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL_ID=qwen2.5:latest
      - AGENT_NAME=SK-Production-Assistant
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs:rw
      - ./test-reports:/app/test-reports:rw
    networks:
      - semantic-kernel-network
    depends_on:
      ollama:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "python", "-c", "from config import app_config; print('Health check passed')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /app/logs
      - /app/test-reports

  # Production Ollama service
  ollama:
    image: ollama/ollama:latest
    container_name: semantic-kernel-ollama-prod
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEP_ALIVE=5m
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - semantic-kernel-network
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    security_opt:
      - no-new-privileges:true

  # Reverse proxy (optional, for production with external access)
  nginx:
    image: nginx:alpine
    container_name: semantic-kernel-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx:rw
    networks:
      - semantic-kernel-network
    depends_on:
      - app-prod
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.2'
    security_opt:
      - no-new-privileges:true
    profiles:
      - nginx
      - web

volumes:
  ollama_data:
    driver: local

networks:
  semantic-kernel-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 