global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Application metrics (from prometheus_client)
  - job_name: 'semantic-kernel-app'
    static_configs:
      - targets: ['metrics-exporter:8000']  # Metrics exporter service
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 10s

  # Ollama service metrics
  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama:11434']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Test execution metrics (file-based for CI/CD)
  - job_name: 'test-metrics'
    file_sd_configs:
      - files:
          - '/etc/prometheus/targets/*.json'
    scrape_interval: 30s
    scrape_timeout: 15s

  # Container metrics from cAdvisor (if available)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 15s

# Alerting configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Storage configuration
storage:
  tsdb:
    retention.time: 7d
    retention.size: 1GB 